version: '3.8'
services:
  bankai:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    hostname: bankai
    working_dir: /root/
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bankai
      - DB_USER=foobar_user
      - DB_PASSWORD=foobar_password
    networks:
      - default
    ports:
      - "3000:3000"
  db:
    image: postgres:alpine
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: unless-stopped
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   depends_on:
  #     - db
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - default
  #   restart: unless-stopped
volumes:
  postgres-db:
networks:
  default:
      name: bankai
      external: true